# Generated by Django 4.1.5 on 2023-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appthree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_three_person',
            name='images',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
